### ISSUE TITLE
Request for detailed descriptions

### ISSUE THREAD

**Issue by akamob** [dksath/gait_recognition#3]
Hi, Thank you for the great work.

I am interested in your work. I want to build a gait analysis framework that detect keypoints of human body and distinguish human identity by analyzing their gait.

I'm wondering if it is possible that you add more detailed descriptions of this repository? including documentation, papers, and tutorials.

Any help is much appreciated.
Thank you:)

**Comment by dksath** [comment]
This repo is still in development as of the moment, in the meantime you could check out the older models which are collated by the OpenGait team, under either our local OpenGait branch or https://github.com/ShiqiYu/OpenGait .  

However, you mentioned that you wanted to detect keypoints of the human body instead of doing a silhouette-based gait analysis. That would fall under pose-based gait estimation, and you could check out the GaitGraph project under https://github.com/tteepe/GaitGraph2 . Thank you for showing your interest in this project!

**Comment by akamob** [comment]
Hi, thank you for your reply.

I am trying to understand these projects and I am looking forward to your codes!

Thank you:)
